# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CARt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CARt
  pod 'M13Checkbox'
  pod 'DropDown'


  target 'CARtTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CARtUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
